// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type Record struct {
	ID            string   `json:"id"`
	Userid        string   `json:"userid"`
	Fileid        string   `json:"fileid"`
	Duration      *float64 `json:"duration"`
	Distance      *float64 `json:"distance"`
	Ascent        *float64 `json:"ascent"`
	Descent       *float64 `json:"descent"`
	Elevationdiff *float64 `json:"elevationdiff"`
	Trails        *string  `json:"trails"`
	Rawdata       *string  `json:"rawdata"`
}

type SpoofedGpx struct {
	ID            string   `json:"id"`
	Duration      *float64 `json:"duration"`
	Distance      *float64 `json:"distance"`
	Highestpoint  *float64 `json:"highestpoint"`
	Lowestpoint   *float64 `json:"lowestpoint"`
	Elevationdiff *float64 `json:"elevationdiff"`
	Trails        *string  `json:"trails"`
	Rawdata       *string  `json:"rawdata"`
}
